CREATE TABLE DEPARTMENT
(
    DEPT_ID SERIAL PRIMARY KEY,
    DEPT_NAME VARCHAR(10)
);

CREATE TABLE STUDENT
(
    STU_ID SERIAL PRIMARY KEY,
    STU_NAME VARCHAR(5),
    DEPT_ID INT REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE,
    DOB DATE,
    PHONE NUMERIC(10),
    EMAIL VARCHAR(15),
    ADDRESS VARCHAR(15)
);

CREATE TABLE STAFF
(
    STAFF_ID SERIAL PRIMARY KEY,
    STAFF_NAME VARCHAR(10),
    DESIGNATION VARCHAR(10),
    DEPT_ID INT REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE
);

CREATE TABLE COURSE
(
    COURSE_ID SERIAL PRIMARY KEY,
    COURSE_NAME VARCHAR(10),
    DEPT_ID INT REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE,
    COURSE_DURATION VARCHAR(5),
    COURSE_CREDITS SMALLINT,
    COURSE_DESCRIPTION VARCHAR(20)
);

CREATE TABLE SUBJECT
(
    SUB_ID SERIAL PRIMARY KEY,
    SUB_NAME VARCHAR(10),
    COURSE_ID INT REFERENCES COURSE(COURSE_ID) ON DELETE CASCADE
);

CREATE TABLE SESSIONS
(
    SESSION_ID SERIAL PRIMARY KEY,
    SUB_ID INT REFERENCES SUBJECT(SUB_ID) ON DELETE CASCADE
);

CREATE TABLE ATTENDANCE
(
    ATTEN_ID SERIAL PRIMARY KEY,
    STU_ID INT REFERENCES STUDENT(STU_ID) ON DELETE CASCADE,
    SESSION_ID INT REFERENCES SESSIONS(SESSION_ID) ON DELETE CASCADE,
    PRESENT CHAR(1)
);

CREATE TABLE RESULT
(
    RESULT_ID SERIAL PRIMARY KEY,
    STU_ID INT REFERENCES STUDENT(STU_ID) ON DELETE CASCADE,
    SUB_ID INT REFERENCES SUBJECT(SUB_ID) ON DELETE CASCADE,
    MARKS SMALLINT
);
